### ISSUE TITLE
Using binary data instead of JSON?

### ISSUE THREAD

**Issue by artuross** [huytd/agar.io-clone#122]
I think client should communicate with server using binary codes, not JSON. Just think about network usage when you have hundreds of players in one realm. Also, binary would decrease GC lag since node would manipulate on less data.

And socket.io, seriously?

BTW., vanilla uses binary codes.

**Comment by RemoveIt** [comment]
#5 duplicate

**Comment by artuross** [comment]
Oh, I'm sorry, didn't notice that one.

**Comment by IgorAntun** [comment]
No problem, just comment there any further suggestions :)
Thanks!

**Comment by RemoveIt** [comment]
also what is wrong with socket.io?

**Comment by RemoveIt** [comment]
http://188.116.52.117:2137/ my game writen with socket.io seems to perform well

**Comment by artuross** [comment]
Nothing, but socket.io is overkill. You should keep client code as small as possible. Just take a look how it keeps growing. Same goes for server. Yaml for config files, socket.io library. And this is the very beginning of this project. And then there's thousand of players on the server. Imagine lag every 30 sec. Is this a game you want to play?

@RemoveIt Probably because you're the only player.

I mean, this project is great, but performance is important ;P

**Comment by RemoveIt** [comment]
@artuross I was thinking about what you just wrote and the only adventage socket.io has over raw websockets is fallback to xhr or flash sockets
but:
1. xhr is too slow
2. if we are using canvas we already need somewhat modern browser                     

we can switch to ws becouse socket.io is giving us nothing

also I dont see any adventage using yaml over json
but I dont think that it has any cost on performance
since it is only running on startup

 I think that thinking about performence upfront( premature optimization) is good idea, also look at code using socket.io vs ws is currently our last butthurt.

**Comment by artuross** [comment]
I mentioned yaml just for completeness. As for ws, I think this is a good idea, socket.io uses ws itself, of course it'll take some rewriting, but this is also a good oportunity to draft protocol spec and implement these two together.

**Comment by jniles** [comment]
I agree, socket.io is a bit overkill. I have used ws before and it is quite speedy. I'd be glad to help with the refactoring.

**Comment by RemoveIt** [comment]
what I have just wrote kill me

**Comment by artuross** [comment]
Hat did u write?

**Comment by RemoveIt** [comment]
derp

**Comment by neslinesli93** [comment]
I think we can easily remove socket.io since it's providing no real advantage for these kinds of low-latency, realtime applications (like a game).
I tried to translate to binary the first messages exchanged between client and server.
I opened a PR just for visibility because we really need this change to happen: see #177

**Comment by justmemaarten** [comment]
How do i set this up???
