### ISSUE TITLE
Screen and arena size

### ISSUE THREAD

**Issue by ajan1** [huytd/agar.io-clone#13]
You can hide enemies, if you have bigger resolution screen than them.

**Comment by huytd** [comment]
Yes. it's a good iodea to have a larger arena size. Most of the code should be done in the client side. I will update this ASAP.

**Comment by Netifriik** [comment]
The arena size should be done server side and the client should only see a fixed size of the arena. The client should see like 10% of the arena size (not dependant of the monitor size) and it should also take under consideration the cell size so that the clients canvas will get a bit larger if the cell grows.

Cell could be fixed at the center like agario. That will make movement speed also better because you don't lose speed at borders since the cell is always at the center.

**Comment by huytd** [comment]
Done by @giongto35 in #41
