### ISSUE TITLE
Small food

### ISSUE THREAD

**Issue by Buskcoin** [huytd/agar.io-clone#232]
The food seems too small in the latest update. Is this a bug?

**Comment by abalabahaha** [comment]
Although somehow the client food config has been at mass: 0.5 since about 20 commits ago, the latest update has *FIXED* food rendering. There was a bug that caused food to render at 5 mass, and now it's rendering at the actual mass defined in foodConfig. Changing line 110 would fix this. Syncing that variable with the server's foodMass config would be even better.
