### ISSUE TITLE
Add virus

### ISSUE THREAD

**Issue by huytd** [huytd/agar.io-clone#25]
It's time to add some virus to the game.
My idea is:
- The virus will be in violet color (#9b59b6 for filling color, #9b50ba for border color)
- Virus also has it's own mass
- Virus can be feed to get more mass (become larger)
- Player will be exploded if he has bigger size than the virus (and he eat it)

More idea?

**Comment by Dietr1ch** [comment]
Virus on agar.io adds an important change to gameplay as throwing food to them makes them divide after a certain size, throwing a half away.
By using that you can effectively throw a virus to a larger cell (player), making them eat the virus and explode onto multiple tiny cells which you can probably eat as they are not much larger than the minimum cell size.

**Comment by Logan7432** [comment]
There still not added.... Like come on there's like no point without them

**Comment by Logan7432** [comment]
abalabahaha why is this so far behind? every other agario server has all viruses and a LOT more options in there configs... is there a way i could host a agario server that has it all the things i need and be able to connect by localhost:3000?

**Comment by TheVoxcraft** [comment]
Coding in. a feature takes time, about a week or maybe less if it was top priority.
And please don't be complaining about, it when you don't know how to code while getting it for free. Nobody is getting paid to make this.

**Comment by TheVoxcraft** [comment]
*Coding in a feature

**Comment by TheVoxcraft** [comment]
I'm replying to Logan7432

**Comment by Logan7432** [comment]
I know coding can take time and I would LOVE to know how to do it I mean if I could I would do it now cause I need to run a private server for school and it's not much fun without viruses and you can't merge, but I guess this is something hard to do since it's taking 4 months. I'll try to learn how to code so I can help for the project or I'm gonna have to find a new clone

**Comment by underGhost** [comment]
I have already implemented viruses and will create a PR for them so you guys can also have them.

**Comment by 3642066** [comment]
You have to try eating virus at original Agar.IO game, after you explode first time, and you get another virus, with many cells, one big and other small cells, instead of exploding, the bigger cell is going to split on 2 big cells with the same size. after that, IF you get another virus, instead of exploding the bigger cell will start groing and much more scores will be received. Thankk you thank you .

**Comment by 3642066** [comment]
Dietr1ch, everybody already knows everything that you describe .

**Comment by 3642066** [comment]
+Logan7432, i have the same difficult you have to install this kid of application. Dont you have internet access at scholl? Its very easy to deploy to a server, where you can use it not only on school. Installing a websocket server is the most complicated thing i ever found. Because server concept is not same concept i learned on old days ... By the way, i need testing users .. have 2 online servers avaiable .

**Comment by 3642066** [comment]
I think that is the best thing people cant code as project main collaborators.. TEsting, its simple, you just need help on testing updates and after that, you need submit review .. As mentioned before, this is not about getting a free game for playing, this is about following a project, coding, testing, and it is better find some way of help, i dont know code for this, but i am trying to do my best, not for have a free game, but i wanna learn coding this thing, and i am learing, canvas, websockets, already learned very much here. I  still dont know anything, but i am here available to do anything other collaborators ask me to do .

**Comment by 3642066** [comment]
I tested this game as much as i could until i find an important bug, and those guys fixed faster i founded and reported it, no one gave me no badges for that .

**Comment by underGhost** [comment]
Can be closed?

**Comment by tunganh03** [comment]
how can i add virus to my agario-clone server?

**Comment by abalabahaha** [comment]
@tunganh03 bots are coming but aren't here _yet_. Also, there is a search feature to search through issues
