### ISSUE TITLE
Legal problem 

### ISSUE THREAD

**Issue by ryush00** [huytd/agar.io-clone#250]
I worried about using this repo.

In their terms, they forbid making site which is similar agar.io
https://agar.io/terms.txt

I just wonder and worry.

**Comment by ryush00** [comment]
Ji

**Comment by jniles** [comment]
Is reverse engineering really illegal? It seems to be very difficult to enforce. Has anyone had any experience with this to inform the discussion?

**Comment by IgorAntun** [comment]
I don't think anyone sane enough would start a sue or whatever against an open-source clone that doesn't even have official servers (we're not even stealing players, actually some people started playing agar.io because of this repo)...

I vote for ragA.io, by the way :trollface:

**Comment by jniles** [comment]
It isn't available. :(

**Comment by MadaraUchiha** [comment]
You cannot patent an idea. They have no legal right to that idea. You aren't allowed to reverse engineer their software and copy their code, and if they've trademarked the name (which they have not, as far as I know) you aren't allowed to use the name.

Since they've done none of the above, they have no legal right to stop anyone from producing an open source "similar piece of software" to their own.

Even if I made a "Killer's Torah" game which is very similar to Assassin's Creed in every imaginable aspect, but took nothing from their code or graphics and made it all myself, they can't do anything more then sending scary letters which are basically "ask me nicely to take it down".

**Comment by jniles** [comment]
I think we can close this then.  If it actually becomes an legal issue, we can seek legal advice.  But for now it's a fun open source project.

**Comment by IgorAntun** [comment]
Good point @MadaraUchiha :+1: 
And yeah, agreed @jniles :)

**Comment by KAMiKAZOW** [comment]
The idea is not a legal issue (esp. since Agar.io is just a multiplayer Osmos) but the name "Agar.io clone" IS a legal issue.

**Comment by MadaraUchiha** [comment]
@KAMiKAZOW It is not, because, again, the name is not trademarked. Just because I called my DI library Chusha, doesn't mean you can't do anything with that name anymore, even if I say so in my README or whatever.

**Comment by hermanjakobi** [comment]
Agar and Agar.io are now trademarks btw

**Comment by IgorAntun** [comment]
That's a good point. I also noticed a few days ago that Agar.IO sent a DCMA Notice to GitHub asking for a repo to be taken down. Perhaps this is something we need to look into now.

https://github.com/github/dmca/blob/master/2015-07-30-Agario.md

**Comment by huytd** [comment]
We are far different from the guy in the URL above, since we're not steal anything of them (Agar.IO and Miniclip) except the name.

As I remembered few months ago, the above repo contains most of the client code (`main.js` or something) and rewrite the server. 

If naming is the problem, and if Miniclip doesn't feel comfortable with it. I think we should change the repo name, for example: ragA as @IgorAntun said =)) 

For sure, at this moment, this is just our "for fun" project, and nobody have any plan to make money with it. And I think Miniclip already checked us at the time they sent a DCMA Note to Github.

**Comment by huytd** [comment]
Btw, we should respect their trademarks.

Please vote with :+1: if you think we should change the repo name

**Comment by abalabahaha** [comment]
:+1:

**Comment by CarlBarr** [comment]
:+1: cells?

**Comment by Buskcoin** [comment]
:thumbsup:

**Comment by MadaraUchiha** [comment]
That DMCA is, pardon my french, bullshit. Have you even read it? They claim that "adding in-game chat" and "multi-server support" infringes them, as if they invented those features. The shape of the cells as well as most of the gameplay is taken off of Osmos, a game far older than Agario. The only thing they have any sort of merit towards is the name, which may or may not be copyrighted, I haven't checked. For that reason, I vote :+1: here.

Please do not be intimidated into changing the gameplay or any aspects of the clone. They have no real claim over any of them.

**Comment by Buskcoin** [comment]
how about "petri" as in petri dish

**Comment by abalabahaha** [comment]
The name is trademarked in the US by Miniclip, so changing it would probably be a good idea. But yeah I don't believe we have any reason to change functionality.

**Comment by huytd** [comment]
Yeah, we only considering about the name. And we will not change any game functionality.

**Comment by huytd** [comment]
OK guys, we will close this issue for now.
