### ISSUE TITLE
Question: difference between io.emit vs socket.emit

### ISSUE THREAD

**Issue by Jared-Sprague** [huytd/agar.io-clone#329]
Hello!
I'm wondering about this peice of code in server.js:
```JavaScript
            io.emit('playerJoin', { name: currentPlayer.name });

            socket.emit('gameSetup', {
                gameWidth: c.gameWidth,
                gameHeight: c.gameHeight
            });
```

I'm wondering what the difference here between, io.emit and socket.emit?
Why don't you just do `socket.emit('playerJoin', { name: currentPlayer.name });`?

Thanks!

**Comment by abalabahaha** [comment]
io.emit tells every single client that a player joined. IIRC this is currently useless and only adds the specially formatted chat message you see on player join.

socket.emit tells that specific socket the game width and height, because the other players already know the game width and height when they joined.

**Comment by Jared-Sprague** [comment]
Ok thank you!
