### ISSUE TITLE
Lack of Updates

### ISSUE THREAD

**Issue by Logan7432** [huytd/agar.io-clone#340]
there have been no changes for 19 days someone please add some stuff! thx

**Comment by abalabahaha** [comment]
How many times do I have to tell you this? People have lives and higher priorities than contributing to open source projects. Please go pay someone if you want things done when you want how you want.

_"**We are not your personal army**"_

**Comment by Logan7432** [comment]
Did i say your my personal army? All I said was when that it hasn't been updated for 19 days when it use to be being worked on every other day. You need to chill out i was only asking a question not to hear how you keep telling me this when I didn't even ask that

**Comment by abalabahaha** [comment]
Sorry, your statement wording kind of came across as a bit commanding and impatient (nothing has happened for 19 days please do stuff thx) (and you didn't write it as a question, but a statement). Still, could you please not file issues because there hasn't been an update? It's not really a real issue if there hasn't been an update, and I think people can read the "last commit 19 days ago" and can decide for themselves whether to contribute or not.

**Comment by IgorAntun** [comment]
> It's not really a _real_ issue if there hasn't been an update
