### ISSUE TITLE
Good, But why?

### ISSUE THREAD

**Issue by Logan7432** [huytd/agar.io-clone#384]
Since i started using this agario clone it has gotten so much better and better! But how come people would use this clone over Cigar Agario? Thats a full agario clone with no bugs and has much more features then this clone. But good job adding viruses into this!

**Comment by huytd** [comment]
Just have a brief search for both of Ogar and Cigar.

So far, this is what I understand: Ogar is just a server implementation to make it work with official agario client, Cigar is another fork of Ogar, added some feature that came with a hacked version of agario client?

If what I'm understand is correct, Cigar are violating Agar's [term](https://agar.io/terms.txt) (and yes, they're saying that it's just for study purpose) so you have to risk your self with the lawyer if you use Cigar. There is another Agar clone repo on Github has been deleted due to this reason. 

About us, we're the completely different implementation, from server side to client side, the common thing between us and official Agar game is the gameplay and... yes, the name. We don't and never copy anything from them. 

I think that's why it might look a bit buggy and the development is really slow but people still coming with us :)

**Comment by Logan7432** [comment]
Thanks! That makes perfect sense
