### ISSUE TITLE
Player name shouldn't grow with cell size

### ISSUE THREAD

**Issue by IgorAntun** [huytd/agar.io-clone#48]
The usernames are growing as you eat more food. That shouldn't happen (unless name fits entirely on cell size, perhaps?)

As it is right now, even if your name overflows the cell size, it'll continue to get bigger as your cell does.

**Comment by fry-** [comment]
I think it would be nice if the name gets bigger when the bubble grows. Because if not, you often can't see the bubble's name if the bubble size is too big. (your viewport is just too little compared to that enemy bubble)

But I agree, this should just be enabled when the bubble grows bigger then the name size.

**Comment by huytd** [comment]
It's not a bug, it's a feature. :trollface: 

Just kidding. 

I intended to do that. But we should have a better way to render player name, to make it always fit inside the circle. :D

**Comment by IgorAntun** [comment]
Yeah the point is it's going out of the cell when using big names :P
